### ISSUE TITLE
How can I use Lexical.FileSystem to modify the file time?

### ISSUE THREAD

**Issue by yaochangyu** [tagcode/Lexical.FileSystem#1]
Hi,
There are  File.SetLastAccessTime, File.SetCreationTime and File.SetLastWriteTime static methods in CLR, it can change file associate time.

How can I use Lexical.FileSystem to modify the file time?

**Comment by tagcode** [comment]
Hello,

I'm, sorry but the library lacks the interface to assign file timestamps. It seems to lack file creation time too. I can't add them atm, too busy. I can merge if someone wants to write one.
